apiVersion: apps/v1 #It is having new features
kind: Deployment
metadata:
  name: myjavaapp-deploy
  labels:
    app: myjavaapp
spec:               #Information about RC
  replicas: 2
  selector:
    matchLabels:
      app: myjavaapp
  template:         #Pod information
    metadata:
      labels:
        app: myjavaapp
    spec:
      containers:
      - name: myjavaapp-container
        image: maha4iac/myonlinebooking:1
        ports:
        - containerPort: 8080
