apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc #rc name
spec:
  replicas: 2 #how many pods you want (we are doing this with the help of RC)
  selector:
    app: myjavaapp               #pod label name and selector label name should be matched.
  template:               #below template, the info belongs to pod
    metadata:
      labels:
        app: myjavaapp           #It should match so that the RC will know which pods' repica to be created.
    spec:
      containers:                #under the pod, we are creating our container
      - name: myjavaapp
        image: maha4iac/mahalogin:1
        ports:
        - containerPort: 80