apiVersion: v1
kind: Service
metadata:          #name and label of service or info about the particulars
  name: myjavaapp-svc
  labels:
    app:  myjavaapp
spec:
  type: NodePort
  ports:
  - port: 8080        #container port number and port fwding port no. should match
    nodePort: 30001
    protocol: TCP
  selector:
    app: mahajavaapp

